server:
  port: 18001
spring:
  application:
      name: car-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: root
  redis:
#    database: 0
#    timeout: 0
##    cluster:
##      nodes:
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    consumer:
     group-id: myGroup
     enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: lucifer
#    username: guest
#    password: guest
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true
#    connection-timeout: 10000
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.entity.*


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30     # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 90  # 发呆时间，即服务续约到期时间（缺省为90s）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  level:
    com:
      FeignClient: debug
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 4000
  ConnecTimeout: 4000
  # 每一台服务器重试的次数，不包含首次调用的那一次
  MaxAutoRetries: 1
  # 重试服务器个数，不包含首次调用的那一台实例
  MaxAutoRetriesNextServer: 2
  http:
    client:
      enabled: true