server:
  port: 18002
spring:
  application:
      name: car-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: root
  redis:
#    database: 0
#    timeout: 0
##    cluster:
##      nodes:
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    consumer:
     group-id: myGroup
     enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: lucifer
#    username: guest
#    password: guest
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true
#    connection-timeout: 10000
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.entity.*


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level: debug